version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: control
      POSTGRES_PASSWORD: control
      POSTGRES_DB: control
  adminer:
    image: adminer
    ports:
      - "8080:8080"